# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calibration_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calibration(object):
    def setupUi(self, Calibration):
        Calibration.setObjectName("Calibration")
        Calibration.resize(263, 172)
        self.verticalLayout = QtWidgets.QVBoxLayout(Calibration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Calibration)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_X_SingleCal = QtWidgets.QLabel(self.tab)
        self.txt_X_SingleCal.setObjectName("txt_X_SingleCal")
        self.horizontalLayout.addWidget(self.txt_X_SingleCal)
        self.UserInput_X_SingleCal = QtWidgets.QLineEdit(self.tab)
        self.UserInput_X_SingleCal.setObjectName("UserInput_X_SingleCal")
        self.horizontalLayout.addWidget(self.UserInput_X_SingleCal)
        self.txt_Y_SingleCal = QtWidgets.QLabel(self.tab)
        self.txt_Y_SingleCal.setObjectName("txt_Y_SingleCal")
        self.horizontalLayout.addWidget(self.txt_Y_SingleCal)
        self.UserInput_Y_SingleCal = QtWidgets.QLineEdit(self.tab)
        self.UserInput_Y_SingleCal.setObjectName("UserInput_Y_SingleCal")
        self.horizontalLayout.addWidget(self.UserInput_Y_SingleCal)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.UserInput_X1_AreaCal = QtWidgets.QLineEdit(self.tab_2)
        self.UserInput_X1_AreaCal.setObjectName("UserInput_X1_AreaCal")
        self.horizontalLayout_3.addWidget(self.UserInput_X1_AreaCal)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.UserInput_Y1_AreaCal = QtWidgets.QLineEdit(self.tab_2)
        self.UserInput_Y1_AreaCal.setObjectName("UserInput_Y1_AreaCal")
        self.horizontalLayout_3.addWidget(self.UserInput_Y1_AreaCal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.UserInput_X2_AreaCal = QtWidgets.QLineEdit(self.tab_2)
        self.UserInput_X2_AreaCal.setObjectName("UserInput_X2_AreaCal")
        self.horizontalLayout_4.addWidget(self.UserInput_X2_AreaCal)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.UserInput_Y2_AreaCal = QtWidgets.QLineEdit(self.tab_2)
        self.UserInput_Y2_AreaCal.setObjectName("UserInput_Y2_AreaCal")
        self.horizontalLayout_4.addWidget(self.UserInput_Y2_AreaCal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txt_scale = QtWidgets.QLabel(Calibration)
        self.txt_scale.setObjectName("txt_scale")
        self.horizontalLayout_5.addWidget(self.txt_scale)
        self.radioButton_Logarithmic = QtWidgets.QRadioButton(Calibration)
        self.radioButton_Logarithmic.setChecked(True)
        self.radioButton_Logarithmic.setObjectName("radioButton_Logarithmic")
        self.horizontalLayout_5.addWidget(self.radioButton_Logarithmic)
        self.radioButton_Linear = QtWidgets.QRadioButton(Calibration)
        self.radioButton_Linear.setObjectName("radioButton_Linear")
        self.horizontalLayout_5.addWidget(self.radioButton_Linear)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Button_ok = QtWidgets.QPushButton(Calibration)
        self.Button_ok.setObjectName("Button_ok")
        self.horizontalLayout_2.addWidget(self.Button_ok)
        self.Button_Calibrate = QtWidgets.QPushButton(Calibration)
        self.Button_Calibrate.setObjectName("Button_Calibrate")
        self.horizontalLayout_2.addWidget(self.Button_Calibrate)
        self.Button_Cancel = QtWidgets.QPushButton(Calibration)
        self.Button_Cancel.setObjectName("Button_Cancel")
        self.horizontalLayout_2.addWidget(self.Button_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Calibration)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Calibration)

    def retranslateUi(self, Calibration):
        _translate = QtCore.QCoreApplication.translate
        Calibration.setWindowTitle(_translate("Calibration", "Form"))
        self.txt_X_SingleCal.setText(_translate("Calibration", "X:"))
        self.txt_Y_SingleCal.setText(_translate("Calibration", "Y:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Calibration", "Single Point Calibration"))
        self.label_4.setText(_translate("Calibration", "X1:"))
        self.label_5.setText(_translate("Calibration", "Y1:"))
        self.label_3.setText(_translate("Calibration", "X2:"))
        self.label_6.setText(_translate("Calibration", "Y2:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Calibration", "Area Calibration"))
        self.txt_scale.setText(_translate("Calibration", "Scale:"))
        self.radioButton_Logarithmic.setText(_translate("Calibration", "Logarithmic"))
        self.radioButton_Linear.setText(_translate("Calibration", "Linear"))
        self.Button_ok.setText(_translate("Calibration", "Ok"))
        self.Button_Calibrate.setText(_translate("Calibration", "Calibrate"))
        self.Button_Cancel.setText(_translate("Calibration", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calibration = QtWidgets.QWidget()
    ui = Ui_Calibration()
    ui.setupUi(Calibration)
    Calibration.show()
    sys.exit(app.exec_())

